### ISSUE TITLE
How should we handle exceptional scenario with this library

### ISSUE THREAD

**Issue by lahirug** [scala/scala-async#137] opened 2015-08-13 00:10 UTC
I can see that cannot put try/finally block, how should I handle that ?

**Comment by pkolaczk** [comment] 2015-10-20 06:44
Adding to this question. How do I handle a failed Future under await?
```scala
async {
  val result = await { thisMayReturnFailedFuture }
}
```

Putting it into a try/catch block is not allowed :(

**Comment by SethTisue** [comment] 2015-10-20 11:28
arguably a duplicate of #76

**Closed** 2020-06-24 06:31 UTC
Labels: duplicate
